import yaml
import sys
from pathlib import Path

path_configWF = sys.argv[1]
dir_MD = Path(sys.argv[2])

with open(path_configWF, "r") as f:
    configWF = yaml.safe_load(f) or {}

dir_ini_MD = Path(configWF.get("dir_ini_MD", str(dir_MD)))

input_params = configWF["lammps"]
if "temperature" in configWF:
    T = configWF["temperature"]  
else:
    T = input_params["T"]


path_FF_MD = Path(configWF.get("path_FF_MD", str(dir_MD)))
print(path_FF_MD)

# LAMMPS input file
lammps_input_file = dir_MD / "lmp.inp"

def w(line=""):
    """Write one LAMMPS command line"""
    f.write(line + "\n")

with open(lammps_input_file, "w") as f:

    # Initialization
    w("# LAMMPS input generated by Python")
    #w("package kokkos newton on neigh half")
    w(f"log {dir_MD / 'log.lammps'}")
    w("\n")

    w(f"units {input_params['units']}")
    w(f"dimension {input_params['dimension']}")
    w(f"boundary {input_params['boundary']}")
    w(f"kspace_style {input_params['kspace_style']}")
    w(f"atom_style {input_params['atom_style']}")
    w("\n")

    path_ini = dir_ini_MD / input_params["ini_MD_file"]

    if input_params["restart"]:
        w(f"read_restart {path_ini}")
        equilibrate = configWF.get("equilibrate", False)
    else:
        w("atom_modify map yes")
        w(f"read_data {path_ini}")
        equilibrate = True

    # Replication
    if "size" in configWF:
        s = configWF["size"]
        if s > 1:
            w(f"replicate {s} {s} {s} bond/periodic")
    elif "replicate" in input_params:
        r = input_params["replicate"]
        w(f"replicate {r[0]} {r[1]} {r[2]} bond/periodic")

    # Force field
    elements = input_params["elements"]
    elements_str = " ".join(elements)

    if configWF["MD_type"] == "lammps+MACE":
        w("newton on")
        w(f"pair_style mliap unified {path_FF_MD} 0")
        w(f"pair_coeff * * {elements_str}")
    elif configWF["MD_type"] == "lammps+VASP":
        w("pair_style vasp")
        w(f"pair_coeff * * {path_FF_MD} {elements_str}")
    else:
        w(f"include {path_FF_MD}")


    # Time step
    w("\n")
    w(f"timestep {input_params['dt']}")
    w("reset_timestep 0")
    w("\n")

    # Thermo output
    w("thermo 100")
    w("thermo_style custom step temp etotal lx ly lz vol density press")
    w("thermo_modify line one format float %12.5f")
    w("\n")

    w("variable t equal step")
    w("variable T equal temp")
    w("variable E equal etotal")
    w("variable X equal lx")
    w("variable Y equal ly")
    w("variable Z equal lz")
    w("variable V equal vol")
    w("variable P equal press")
    w("\n")

    w(
        f"fix thermolog all print 100 "
        f"'$t $T $E $X $Y $Z $V $P' "
        f"file {dir_MD / 'thermo_output.txt'} screen no"
    )

    T_damp = input_params["T_damp"]
    prodrun_stepsize = input_params["prodrun_stepsize"]

    # Equilibration
    if equilibrate:

        w(
            f"dump 0 all custom {prodrun_stepsize} "
            f"{dir_MD / 'position_eq.lammpstrj'} "
            "id type element x y z"
        )
        w("dump_modify 0 sort id")
        w(f"dump_modify 0 element {elements_str}")
        w("\n")

        T_start = input_params.get("T_start", T)

        if not input_params["restart"]:
            w(f"velocity all create {T_start} 12345 dist gaussian")
            #w("minimize 1.0e-4 1.0e-6 100 1000")
            w(" ")

        # Heating phase
        if T_start != T:
            w(f"fix 1 all nvt temp {T_start} {T} {T_damp}")
            w(f"run {input_params['eqsteps_nvt_heating']}")
            w("unfix 1")
            w("\n")

        # NVT run
        w(f"fix 1 all nvt temp {T} {T} {T_damp}")
        w(f"run {input_params['eqsteps_nvt']}")
        w("unfix 1")
        w("\n")

        # NPT run
        P = input_params.get("P", 0.0)
        P_damp = input_params.get("P_damp", 100.0)

        w(f"fix 1 all npt temp {T} {T} {T_damp} aniso {P} {P} {P_damp}")
        w(f"run {input_params['eqsteps_npt']}")
        w("unfix 1")
        w("\n")

        w(f"write_restart {dir_MD / f'restart_eq_{T}'}")
        w("undump 0")
        w("\n")

    # Pre-production
    w(f"write_data {dir_MD / 'pre_run.data'}")

    # Dump settings
    w(
        f"dump 1 all custom {prodrun_stepsize} "
        f"{dir_MD / 'position.lammpstrj'} id type x y z"
    )
    w("dump_modify 1 sort id")
    w(f"dump_modify 1 element {elements_str}")

    w(
        f"dump 2 all custom {prodrun_stepsize} "
        f"{dir_MD / 'velocity.lammpstrj'} id type vx vy vz"
    )
    w("dump_modify 2 sort id")
    w(f"dump_modify 2 element {elements_str}")

    w(
        f"dump 3 all custom {prodrun_stepsize} "
        f"{dir_MD / 'forces.lammpstrj'} id type fx fy fz"
    )
    w("dump_modify 3 sort id")
    w(f"dump_modify 3 element {elements_str}")
    w("\n")

    # NVT production run
    w(f"fix 1 all nvt temp {T} {T} {T_damp}")
    w(f"run {input_params['prodrun_numsteps']}")
    w("unfix 1")

    w(f"write_restart {dir_MD / f'restart_{T}'}")

print(f"LAMMPS input file written to: {lammps_input_file}")
