import os
import subprocess
from typing import Tuple
from ruamel.yaml import YAML
from pathlib import Path
import shutil


def is_missing_or_empty(path: Path | str) -> bool:
    p = Path(path)
    return not p.exists() or (p.is_dir() and not any(p.iterdir()))


def lammps_trajectory_to_xdatcar(traj_path: Path, xdatcar_path: Path, elements: list):
    """Convert a LAMMPS dump trajectory into a VASP XDATCAR.

    The LAMMPS production dump (``position.lammpstrj``, columns
    ``id type element x y z``) is read with ASE and the atoms are regrouped by
    species in the order given by ``elements`` so the XDATCAR header matches the
    POTCAR concatenation order (e.g. ``Ta Cu N``). vamp can then sample POSCARs
    from it exactly as it does from an externally supplied XDATCAR.
    """
    from ase.io import read
    from ase.io.vasp import _write_xdatcar_header, _write_xdatcar_config

    frames = read(str(traj_path), format="lammps-dump-text", index=":")
    if not isinstance(frames, list):
        frames = [frames]

    # ASE picks up the chemical symbols from the dump's ``element`` column
    # (written by ``dump_modify ... element ...``). Validate they match the
    # configured species so a missing element column fails loudly instead of
    # silently producing H/He/Li dummies.
    symbols = frames[0].get_chemical_symbols()
    if set(symbols) != set(elements):
        raise Exception(
            f"Elements in the LAMMPS trajectory {sorted(set(symbols))} do not "
            f"match the configured 'lammps: elements' {sorted(set(elements))}. "
            "Ensure the dump has an 'element' column (dump_modify ... element ...)."
        )

    # One permutation, applied to every frame, grouping atoms by species in
    # ``elements`` order so the XDATCAR header is valid (grouped species/counts).
    order = [i for el in elements for i, s in enumerate(symbols) if s == el]
    frames = [f[order] for f in frames]

    # ASE's own `write(..., format="vasp-xdatcar")` re-emits the full header
    # (including the lattice) before every "Direct configuration=" block,
    # which `vamp supercell sample` chokes on for a fixed-cell trajectory. So
    # write the header once ourselves, then one config block per frame.
    with open(xdatcar_path, "w") as f:
        _write_xdatcar_header(f, frames[0], label=None)
        for i, frame in enumerate(frames, start=1):
            _write_xdatcar_config(f, frame, i)
    print(f"Converted {len(frames)} MD frames -> {xdatcar_path}", flush=True)


def iter_dft_dirs(dir_project: Path):
    directories = os.listdir(dir_project)
    dft_dirs = [d for d in directories if d.startswith("config_")]
    for dft_dir in dft_dirs:
        dft_dir_path = dir_project / dft_dir
        if dft_dir_path.is_dir():
            yield dft_dir_path


def format_incar_value(value) -> str:
    """Format a Python value as a VASP INCAR value."""
    if isinstance(value, bool):
        return ".TRUE." if value else ".FALSE."
    if isinstance(value, (list, tuple)):
        return " ".join(format_incar_value(v) for v in value)
    return str(value)


def write_incar(vasp_params: dict, incar_path: Path):
    """
    Write a VASP INCAR file from the parameters of the "vasp" config group.

    Each key/value pair becomes one ``TAG = value`` line. Tags are upper-cased
    (VASP convention), booleans are rendered as ``.TRUE.``/``.FALSE.`` and
    lists are written as space-separated values.
    """
    with open(incar_path, "w") as f:
        f.write("# INCAR generated by Flow-Otter\n")
        for key, value in vasp_params.items():
            f.write(f"{key.upper()} = {format_incar_value(value)}\n")


def write_kpoints(kpoints_params: dict, kpoints_path: Path):
    """
    Write a VASP KPOINTS file from the parameters of the "kpoints" config group.

    Generates an automatic Gamma-centred / Monkhorst-Pack mesh::

        kpoints:
          type: Gamma          # "Gamma" or "Monkhorst-Pack" (default: Gamma)
          mesh: [4, 4, 4]      # subdivisions along each reciprocal axis
          shift: [0, 0, 0]     # optional shift (default: 0 0 0)
    """
    mesh = kpoints_params.get("mesh")
    if not mesh:
        raise Exception(
            "The 'kpoints' config group requires a 'mesh' entry, e.g. "
            "mesh: [4, 4, 4]."
        )
    kpoints_type = kpoints_params.get("type", "Gamma")
    shift = kpoints_params.get("shift", [0, 0, 0])
    with open(kpoints_path, "w") as f:
        f.write("# KPOINTS generated by Flow-Otter\n")
        f.write("0\n")  # 0 = automatic mesh generation
        f.write(f"{kpoints_type}\n")
        f.write(" ".join(str(m) for m in mesh) + "\n")
        f.write(" ".join(str(s) for s in shift) + "\n")


def main(
    path_configWF: str = "workflow_config.yaml", num_simulations: int = 1, **kwargs
) -> Tuple[bool, dict]:
    """
    Task to prepare DFT calculations from MD snapshots. Requires a trajectory file (vasp xdatcar format)
    to be provided in the workflow configuration file. The trajectory file is copied to the project directory
    and then sampled using Vampires to extract snapshots for DFT calculations. The number of snapshots to sample can be
    specified in the workflow configuration file (N_snapshots).
    The task returns a dictionary with the path to the configuration file and the number of simulations.
    """

    print("Start task: prep_DFT", flush=True)

    yaml = YAML()

    with open(path_configWF, 'r') as f:
        configWF = yaml.load(f)

    dir_project = Path(configWF.get("dir_project", "./"))

    # Handle multiple simulations (branching)
    if num_simulations > 1:
        i = kwargs['pq_index'][0]

        # determine correct branch config file
        param_to_vary = configWF["param_to_vary"]
        array_to_vary = configWF["array_to_vary"]

        
        dir_project_i = dir_project / f"{param_to_vary}_{array_to_vary[i]}/"
        path_configWF_i = dir_project_i / 'branch_config.yaml'

        with open(str(path_configWF_i), 'r') as f:
            configWF_i = yaml.load(f)

    else:
        configWF_i = configWF.copy()
        dir_project_i = dir_project

    dft_dir = dir_project_i / "2-DFT"
    dft_dir.mkdir(parents=True, exist_ok=True)

    trajectory_file_path = configWF_i.get("trajectory_file", None)
    if trajectory_file_path is not None:
        # Case 1: an external trajectory (VASP XDATCAR) was supplied directly.
        trajectory_file_path = Path(trajectory_file_path)
        if not trajectory_file_path.exists():
            raise Exception(f"Provided trajectory file {trajectory_file_path} does not exist.")

        shutil.copy(trajectory_file_path, dft_dir / "XDATCAR")

    else:
        # Case 2: no external trajectory -> build the XDATCAR on the fly from
        # the MD stage that ran for this branch (MD_type: lammps).
        dir_MD = Path(configWF_i.get("dir_MD", str(dir_project_i / "1-MD/")))
        md_traj_name = configWF_i.get("md_trajectory_file", "position.lammpstrj")
        md_traj_path = dir_MD / md_traj_name

        if not md_traj_path.exists():
            raise Exception(
                f"No 'trajectory_file' was provided and no MD trajectory was found "
                f"at {md_traj_path}. Run an MD stage first (set MD_type: lammps) or "
                "supply 'trajectory_file' in the configuration."
            )

        elements = (configWF_i.get("lammps") or {}).get("elements")
        if not elements:
            raise Exception(
                "Converting a LAMMPS trajectory to XDATCAR requires the "
                "'lammps: elements: [...]' list, which sets the species order of "
                "the XDATCAR (and must match the POTCAR concatenation order)."
            )

        lammps_trajectory_to_xdatcar(md_traj_path, dft_dir / "XDATCAR", elements)

    # use Vampires to sample snapshots from the trajectory
    n_snapshots = configWF.get("N_snapshots", 10)
    subprocess.run(
        [
            "vamp",
            "supercell",
            "sample",
            "--N",
            str(n_snapshots),
        ],
        cwd=dft_dir,
        check=True,
    )

    def copy_file_to_project(file_key: str):
        file_path = configWF_i.get(file_key)
        if file_path is not None:
            file_path = Path(file_path)
            if not file_path.exists():
                raise Exception(f"Provided {file_key} file {file_path} does not exist.")

            for snapshot_dir in iter_dft_dirs(dft_dir):
                shutil.copy(file_path, snapshot_dir / file_path.name)

    # copy the DFT input files to the project directory
    for file in ["potcar_file"]:
        copy_file_to_project(file)

    # create the INCAR files from the "vasp" config group (compare the "lammps"
    # group used to write the LAMMPS input)
    vasp_params = configWF_i.get("vasp")
    if not vasp_params:
        raise Exception(
            "No 'vasp' parameter group found in the configuration file. "
            "Add a 'vasp' group with the INCAR tags to be written."
        )
    for snapshot_dir in iter_dft_dirs(dft_dir):
        write_incar(vasp_params, snapshot_dir / "INCAR")

    # create the KPOINTS files from the "kpoints" config group
    kpoints_params = configWF_i.get("kpoints")
    if not kpoints_params:
        raise Exception(
            "No 'kpoints' parameter group found in the configuration file. "
            "Add a 'kpoints' group with the mesh to be written."
        )
    for snapshot_dir in iter_dft_dirs(dft_dir):
        write_kpoints(kpoints_params, snapshot_dir / "KPOINTS")

    return True, {"path_configWF": path_configWF, "num_simulations": num_simulations}
